#!/bin/sh
set -e

# shellcheck disable=SC2016
: '
sudo apt-get install curl -y

1. install openssh -y
sudo apt-get install openssh-server -y
sudo systemctl enable ssh
sudo systemctl start ssh
---

2. install git
sudo apt-get install git -y
add git ssh key
---

3. install docker + docker compose
curl -fsSL https://get.docker.com -o get-docker.sh
--> 3.1 add docker user -- no sudo
sudo sh ./get-docker.sh
sudo groupadd docker
sudo usermod -aG docker $USER
newgrp docker
---

4. mqtt
cd /o7k/o7k-station/images/mosquitto
docker compose up -d
--

5. zibgee2mqtt
cd /o7k/o7k-station/images/zigbee2mqtt
change mosquitto ip in config
setup new network in docker
$ docker network create -d bridge NAME_OF_NETWORK
add mqtt container ip to config
--

6. setup haas
docker compose up -d
cd /o7k/o7k-station/images/hass
docker compose up -d

--
7. setup backup
add gsuit -> https://cloud.google.com/sdk/docs/install#deb and authenticate
add cronjob to crontab
echo "0 3 * * *  bash /o7k/o7k-station/backup/backup >> /o7k/o7k-station/backup/backup.log 2>&1"

set bucker life cycle - remove files older than 14 days
gsutil lifecycle set ./bucket_rule.json gs://name-of-bucket <- set lifecycle
'
