version: '3'
services:
  homeassistant:
    container_name: hass
    image: homeassistant/home-assistant:stable
    volumes:
      - ../../configs/haas:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
    network_mode: host
