apiVersion: apps/v1
kind: Deployment
metadata:
  name: volumesnapshot-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volumesnapshot-controller
  template:
    metadata:
      labels:
        app: volumesnapshot-controller
    spec:
      serviceAccountName: volumesnapshot-controller
      containers:
        - name: volumesnapshot-controller
          image: kubernetes-sigs/snapshot-controller:v4.0.0
          command:
            - /snapshot-controller
            - --v=5
            - --leader-election
          volumeMounts:
            - name: kubernetes-sigs
              mountPath: /tmp
        - name: csi-snapshotter
          image: kubernetes-csi/csi-snapshotter:v4.0.0
          args:
            - --csi-address=$(ADDRESS)
            - --leader-election
          env:
            - name: ADDRESS
              value: /run/csi/socket
          volumeMounts:
            - name: kubernetes-csi
              mountPath: /run/csi/socket
      volumes:
        - name: kubernetes-sigs
          emptyDir: {}
        - name: kubernetes-csi
          hostPath:
            path: /var/lib/kubelet/plugins/kubernetes.io/csi

