apiVersion: apps/v1
kind: Deployment
metadata:
  name: hass-deployment
spec:
  selector:
    matchLabels:
      app: hass
  replicas: 1
  template:
    metadata:
      labels:
        app: hass
    spec:
      volumes:
        - name: hass-storage
          persistentVolumeClaim:
            claimName: hass-pvc
      containers:
        - name: hass
          image: homeassistant/home-assistant:stable
          ports:
            - containerPort: 8123
          volumeMounts:
            - mountPath: /config
              name: hass-storage
          securityContext:
            privileged: true
