#!/bin/bash

set -e

readonly SOURCE_DIR="/o7k/o7k-station/configs"
readonly COMPOSE_DIR="/o7k/o7k-station/images"
readonly BACKUP_DIR="/o7k/o7k-station/backup"

now=$(date +'%m-%d-%Y')
name="o7k-${now}.tar.gz"

cd $COMPOSE_DIR

docker compose down

cd $BACKUP_DIR

tar -cvzf $name $SOURCE_DIR

gsutil cp $name gs://o7k-station-backup

rm $name

cd $COMPOSE_DIR

docker compose up -d
