apiVersion: v1
kind: Service
metadata:
  name: home-assistant-service
spec:
  selector:
    app: hass
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
      nodePort: 30001
  type: NodePort
