apiVersion: apps/v1
kind: Deployment
metadata:
  name: hass-deployment
spec:
  selector:
    matchLabels:
      app: hass
  replicas: 1
  template:
    metadata:
      labels:
        app: hass
    spec:
      volumes:
        - name: zigbee
          hostPath:
            path: /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0
            type: CharDevice
        - name: velbus
          hostPath:
            path: /dev/serial/by-id/usb-Velleman_Projects_VMB1USB_Velbus_USB_interface-if00
            type: CharDevice
        - name: hass-storage
          persistentVolumeClaim:
            claimName: hass-pvc
      containers:
        - name: hass
          image: homeassistant/home-assistant:stable
          ports:
            - containerPort: 8123
          volumeMounts:
            - mountPath: /dev/serial/by-id/usb-Velleman_Projects_VMB1USB_Velbus_USB_interface-if00
              name: velbus
            - mountPath: /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0
              name: zigbee
            - mountPath: /config
              name: hass-storage
          securityContext:
            privileged: true
