apiVersion: v1
kind: PersistentVolume
metadata:
  name: hass-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /o7k/configs/hass
