apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: velero-backup
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: velero
            image: velero/velero:latest
            command:
            - /velero
            args:
            - backup
            - create
            - --include-namespaces=default
            - --include-resources=persistentvolumes,persistentvolumeclaims
            - --snapshot-volumes
            - $(date +%Y%m%d%H%M%S)
          restartPolicy: OnFailure