mqtt:
  host: mqtt://mqtt-service
  port: 1883
  user: {FRIGATE_MQTT_USER}
  password: {FRIGATE_MQTT_PASSWORD}
go2rtc:
  streams:
    cam:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.164:554/h264Preview_01_main
    cam_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.164:554/h264Preview_01_sub
cameras:
  cam:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.164:554/h264Preview_01_main
          roles:
            - rtmp
            - detect
    detect:
      enabled: false