homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: '!secret.yaml server'
  user: '!secret.yaml user'
  password: '!secret.yaml password'
  ca: '/etc/ssl/mqtt-ca.crt'
  # Optional: absolute paths to SSL/TLS key and certificate for client-authentication (default: nothing)
  key: '/etc/ssl/mqtt-client.key'
  cert: '/etc/ssl/mqtt-client.crt'
frontend: true
serial:
  port: /dev/ttyACM0
devices:
  '0x00158d0008a7047d':
    friendly_name: '0x00158d0008a7047d'
