homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://172.25.0.3:1883
frontend: true
serial:
  port: /dev/ttyACM0
devices:
  '0x00158d0008a7047d':
    friendly_name: '0x00158d0008a7047d'
