apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frigate
  template:
    metadata:
      labels:
        app: frigate
    spec:
      volumes:
      - name: coral
        hostPath:
          path: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
          type: CharDevice
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: config-volume
        hostPath:
          path: /o7k/configs/frigate/config
      - name: storage-volume
        hostPath:
          path: /o7k/configs/frigate/storage
      - name: cache-volume
        emptyDir:
          medium: Memory
          sizeLimit: "300Mi"
      containers:
      - name: frigate
        image: ghcr.io/blakeblackshear/frigate:stable
        ports:
        - containerPort: 5000
        - containerPort: 8554
        - containerPort: 8555
        env:
        - name: FRIGATE_REOLINK_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: frigate-reolink
        - name: FRIGATE_REOLINK_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: frigate-reolink
        - name: FRIGATE_DAHUA_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: frigate-adhua
        - name: FRIGATE_DAHUA_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: frigate-adhua
        volumeMounts:
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
        - mountPath: /config
          name: config-volume
        - mountPath: /media/frigate
          name: storage-volume
        - mountPath: /tmp/cache
          name: cache-volume
        - mountPath: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
          name: coral
        securityContext:
          privileged: true
