apiVersion: v1
kind: Service
metadata:
  name: home-assistant-service
spec:
  selector:
    app: hass
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
      nodePort: 31883
  type: NodePort
