apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-cronjob
spec:
  schedule: "0 0 * * MON"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: hass-storage
            persistentVolumeClaim:
              claimName: hass-pvc
          - name: gcp-credentials
            secret:
              secretName: gcp-credentials
          containers:
          - name: backup
            image: remigiu6z/backup-gcp:latest
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: hass-storage
              mountPath: /config
            - name: gcp-credentials
              mountPath: /var/secrets/google
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/credentials.json
            command:
            - /bin/sh
            - -c
            - |
              DATE=$(date +%Y%m%d)
              tar -czvf /hass_$DATE.tar.gz /config && \
              /root/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS} \
              /root/google-cloud-sdk/bin/gsutil cp /hass_$DATE.tar.gz gs://o7k
          restartPolicy: OnFailure
      backoffLimit: 4