apiVersion: batch/v1
kind: Job
metadata:
  name: backup-job
spec:
  template:
    spec:
      volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: my-pvc
      - name: gcp-credentials
        secret:
          secretName: gcp-credentials
      containers:
      - name: backup
        image: remigiu6z/backup-gcp:latest
        volumeMounts:
        - name: hass-storage
          mountPath: /config
        - name: gcp-credentials
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/credentials.json
        command:
        - /bin/sh
        - -c
        - |
          tar -czvf /hass.tar.gz /config && \
          gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS} && \
          gsutil cp /hass.tar.gz gs://o7k
      restartPolicy: Never
  backoffLimit: 4
