apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./frigate/frigate-deployment.yaml
- ./frigate/frigate-service.yaml
- ./hass/hass-deployment.yaml
- ./hass/hass-pv.yaml
- ./hass/hass-pvc.yaml
- ./hass/hass-service.yaml
- ./storage/storage-class.yaml
